name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      #Flake for python
      - name: Install flake8
        run: pip install flake8

      - name: Lint Python
        run: flake8 api worker

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install JS deps
        run: |
          cd frontend
          bun install

      - name: Lint JavaScript
        run: |
          cd frontend
          bunx eslint .

      # Docker
      - name: Find and lint Dockerfiles
        run: |
          find . -name "Dockerfile" -print0 | while IFS= read -r -d '' file; do
          echo "Linting $file"
          docker run --rm -i hadolint/hadolint < "$file"
          done
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install test dependencies
        run: |
          pip install -r api/requirements-test.txt
          pip install -r api/requirements.txt

      - name: Run tests with coverage
        run: |
          PYTHONPATH=. pytest tests \
            --cov=api \
            --cov-report=html:htmlcov \
            -v

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: htmlcov/
          if-no-files-found: error

  build:
    runs-on: ubuntu-latest
    needs: test

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v4

      - name: Set SHA
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build API image
        run: |
          docker build -t localhost:5000/api:$SHA -t localhost:5000/api:latest ./api

      - name: Build frontend image
        run: |
          docker build -t localhost:5000/frontend:$SHA -t localhost:5000/frontend:latest ./frontend

      - name: Build worker image
        run: |
          docker build -t localhost:5000/worker:$SHA -t localhost:5000/worker:latest ./worker

      - name: Save images as tarballs
        run: |
          docker save localhost:5000/api:latest     -o api.tar
          docker save localhost:5000/frontend:latest -o frontend.tar
          docker save localhost:5000/worker:latest   -o worker.tar

      - name: Upload image tarballs
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            api.tar
            frontend.tar
            worker.tar
          if-no-files-found: error
      - name: Push images
        run: |
          docker push localhost:5000/api:$SHA
          docker push localhost:5000/api:latest

          docker push localhost:5000/frontend:$SHA
          docker push localhost:5000/frontend:latest

          docker push localhost:5000/worker:$SHA
          docker push localhost:5000/worker:latest

  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download image tarballs
        uses: actions/download-artifact@v4
        with:
          name: docker-images

      - name: Load images into Docker
        run: |
          docker load -i api.tar
          docker load -i frontend.tar
          docker load -i worker.tar

      - name: Install Trivy
        run: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
      - name: Scan API image
        run: |
          trivy image --exit-code 1 --severity CRITICAL \
            --format sarif --output trivy-api.sarif \
            localhost:5000/api:latest
      - name: Scan Worker image
        run: |
          trivy image --exit-code 1 --severity CRITICAL \
            --format sarif --output trivy-worker.sarif \
            localhost:5000/worker:latest
      - name: Scan Frontend image
        run: |
          trivy image --exit-code 1 --severity CRITICAL \
            --format sarif --output trivy-frontend.sarif \
            localhost:5000/frontend:latest

      - name: Upload Trivy results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-results
          path: "*.sarif"
          if-no-files-found: warn

  integration-test:
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - uses: actions/checkout@v4

      # - name: Set up Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: "1.22"

      - name: Download image tarballs
        uses: actions/download-artifact@v4
        with:
          name: docker-images

      - name: Load built images
        run: |
          docker load -i api.tar
          docker load -i worker.tar
          docker load -i frontend.tar

      - name: Run Integration test
        run: |
          cp .env.example .env
          docker compose up -d --no-build

      - name: Dump logs on failure
        if: failure()
        run: |
          docker compose logs
          docker inspect hng14-stage2-devops-api-1 \
            | jq '.[0].State | {Status, ExitCode, OOMKilled, Error, Health}'

      - name: Query API state
        if: failure()
        run: |
          docker exec hng14-stage2-devops-api-1 ps aux
          docker exec hng14-stage2-devops-api-1 lsof -i :8000
          docker exec hng14-stage2-devops-api-1 sh -c 'lsof -i :${API_PORT}'

  deploy:
    runs-on: ubuntu-latest
    needs: integration-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy
        run: echo "Deploying main branch build"
