name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      #Flake for python
      - name: Install flake8
        run: pip install flake8

      - name: Lint Python
        run: flake8 api worker

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install JS deps
        run: |
          cd frontend
          bun install

      - name: Lint JavaScript
        run: |
          cd frontend
          bunx eslint .

      # Docker
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: |
            api/Dockerfile_api
            frontend/Dockerfile
            worker/Dockerfile
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install test dependencies
        run: |
          pip install -r api/requirements-test.txt

      - name: Run tests with coverage
        run: |
          pytest api/tests --cov=api --cov-report=html -v

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: api/htmlcov/
          if-no-files-found: error

  build:
    runs-on: ubuntu-latest
    needs: test

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v4

      - name: Set SHA
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build API image
        run: |
          docker build -t localhost:5000/api:$SHA -t localhost:5000/api:latest ./api

      - name: Build frontend image
        run: |
          docker build -t localhost:5000/frontend:$SHA -t localhost:5000/frontend:latest ./frontend

      - name: Build worker image
        run: |
          docker build -t localhost:5000/worker:$SHA -t localhost:5000/worker:latest ./worker

      - name: Push images
        run: |
          docker push localhost:5000/api:$SHA
          docker push localhost:5000/api:latest

          docker push localhost:5000/frontend:$SHA
          docker push localhost:5000/frontend:latest

          docker push localhost:5000/worker:$SHA
          docker push localhost:5000/worker:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy
        run: echo "Deploying main branch build"
